name: Playwright Tests

on:
  push:
  pull_request:

jobs:

  ui-e2e:
    name: UI E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - run: npx playwright install --with-deps

      # 🔥 Run only UI tagged tests
      - run: npm run test:ui:e2e

      - name: Upload UI Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-ui-report
          path: playwright-report/

  api-e2e:
    name: API E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      # 🔥 Run only API tests
      - run: npm run test:api:e2e

      - name: Upload API Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-api-report
          path: playwright-report/